### ISSUE TITLE
Stream and LazyList are not serializable

### ISSUE THREAD

**Issue by lrytz** [scala/collection-strawman#541] opened 2018-04-04 12:50 UTC
```
scala> new java.io.ObjectOutputStream(new java.io.ByteArrayOutputStream()).writeObject(LazyList(1,2,3))
java.io.NotSerializableException: scala.collection.immutable.LazyList$Cons
```

Once fixed, re-enable the tests in `test/files/run/serialize-stream.scala`, `test/files/jvm/serialization-new.scala`, `test/files/jvm/serialization.scala` and run`--update-check` (marked with `TODO-newColl`).

**Comment by SethTisue** [comment] 2018-05-04 15:54
duplicate of #331

**Closed by SethTisue** 2018-05-04 15:54 UTC
