### ISSUE TITLE
Add a LinkedMap/VectorMap in 2.13.x

### ISSUE THREAD

**Issue by mdedetrich** [scala/collection-strawman#293] opened 2017-11-11 16:23 UTC
As detailed here https://contributors.scala-lang.org/t/clarification-on-dependencies-in-sp-scalajson-vectormap/1305/8, I have come across the situation where I need to add an immutable Map like data structure that maintains key ordering while still having effectively constant lookup time on all operations.

Currently the only known way to do this is to have a composite datastrcuture that maintains an immutable HashMap/Vector underneath. The `HashMap` is used for queries on key while the `Vector` is used for queries on index.

This issue is to discuss whether it makes sense to add this collection to the collection-strawman, and if so how this should be done in light of https://github.com/mdedetrich/linked-map (i.e. should we keep the naming of the collections consistent between this library and the newly added collection to the strawman).

Furthermore there are some design impliciations, i.e. https://github.com/mdedetrich/linked-map adds a LinkedMap trait (which is trait that signifies that an immutable Map maintains key ordering). It would make sense to make `ListMap` in the collections strawman extend this trait, while providing the new `VectorMap` (which also extends `LinkedMap`). Unfortunately this isn't really possible in the current standard library collections since we can't change already existing classes.

If we decide to do this, we should also decide on matters like naming

**Comment by lihaoyi** [comment] 2017-11-12 00:42
Duplicate of https://github.com/scala/collection-strawman/issues/277?

**Comment by julienrf** [comment] 2017-11-13 08:41
Indeed, I suggest we close this issue and continue the discussion in #277.

**Closed by julienrf** 2017-11-13 08:41 UTC
