### ISSUE TITLE
StrawmanTest.mainTest failing in Scala 2.13.0-M3

### ISSUE THREAD

**Issue by SethTisue** [scala/collection-strawman#308] opened 2017-11-30 14:25 UTC
```
[collection-strawman] [error] Test strawman.collection.test.StrawmanTest.mainTest failed: java.lang.AssertionError: assertion failed, took 0.472 sec
[collection-strawman] [error]     at scala.Predef$.assert(Predef.scala:204)
[collection-strawman] [error]     at strawman.collection.test.StrawmanTest.lazyListOps(Test.scala:466)
[collection-strawman] [error]     at strawman.collection.test.StrawmanTest.mainTest(Test.scala:576)
[collection-strawman] [error]     ...
```

details at https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/856/consoleFull

doesn't seem to be intermittent (failed in both runs last night)

**Comment by SethTisue** [comment] 2017-11-30 14:27
or, hmm, maybe it is intermittent, there is a run currently in progress where collection-strawman already went green: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/857/consoleFull

we'll see how the next few runs go

**Comment by julienrf** [comment] 2017-11-30 15:54
Did you change something about the evaluation of by-name right-associative operators?

**Comment by julienrf** [comment] 2017-11-30 15:56
Yeah now I remember that one: https://github.com/scala/scala/pull/5969

But the test should _always_ fail with the new evaluation model.

**Comment by SethTisue** [comment] 2017-11-30 17:28
I failed to notice that run 857 was manually triggered by Miles against a different 2.13 build.

So yes, always failing.

**Comment by julienrf** [comment] 2017-12-07 11:03
Hey @SethTisue! What should we do about that? Is this blocking you?

**Comment by SethTisue** [comment] 2017-12-11 23:19
it's not blocking me.

I don't understand the issue, I don't know what you should do. but in general, this repo ought to compile, and tests pass, on whatever the latest 2.13 nightly is, since before long some descendant of that nightly will become 2.13.0-M3. (@szeiger?)

**Comment by julienrf** [comment] 2017-12-12 07:56
The issue is that we have a test that checks the semantics of an operation (`#::` on ~`Stream`~ `LazyList`) and that this semantics has changed because the language has changed. I would be in favor of changing the test so that it takes the new language semantics into account. However, the fact that the semantics of `#::` will have changed between 2.12 and 2.13 might be a problem for existing users, though I doubt something relies on the fact that this operator is not really lazy.

**Comment by SethTisue** [comment] 2017-12-12 16:11
> I would be in favor of changing the test so that it takes the new language semantics into account

👍

**Comment by julienrf** [comment] 2018-01-15 11:04
@szeiger I tried to make `#::` a proper method on `LazyList` (rather than an extension method), like you did in https://github.com/scala/scala/pull/5969 but then I noticed that it was not anymore possible to define lazy lists via recursive lazy vals:

~~~ scala
lazy val fibs: LazyList[Int] = 0 #:: 1 #:: fibs.zip(fibs.tail).map { case (prevPrev, prev) => prev + prevPrev }
~~~

We get an infinite recursion. Is that expected?

Note that on one hand, @odersky thinks that recursive lazy vals should not be supported (https://github.com/lampepfl/dotty/pull/1892#issuecomment-271530182). On the other hand, being able to define the fibonacci sequence as shown above would be useful, in my opinion.

**Comment by SethTisue** [comment] 2018-01-16 20:19
here's an example recursive lazy val `Stream` in my own code:

```
  implicit class RichStream[T](private val s: Stream[T]) extends AnyVal {
    // if we put the lazy val at the top level, we can't extend AnyVal,
    // so we make it local, like this:
    def circular: Stream[T] = {
      lazy val result: Stream[T] = s #::: result
      result
    }
}
```

the use of `lazy val` gives a true cycle (infinite if traversed, but occupying constant space in memory). still a niche use case, I guess, and wouldn't be horrible with a local `var` :-\

**Comment by szeiger** [comment] 2018-01-17 13:28
The Fibonacci example desugars to:

```
lazy val fibs: LazyList[Int] =
  fibs.zip(fibs.tail).map { case (prevPrev, prev) => prev + prevPrev }.#::(1).#::(0)
```

Since the receiver of a method call cannot be lazy, this will never work. We still need an extension method. The improvement by the new desugaring is that `0` is no longer forced (and `1` if `#::` is not a lazy extension method).

**Comment by julienrf** [comment] 2018-04-20 09:27
Fixed by https://github.com/scala/scala/pull/6509

**Closed by julienrf** 2018-04-20 09:27 UTC
Labels: blocker, in progress
